livewire/flux

- composer.json
The docs say Laravel 10 is supported, but the actual requirements don't permit that.
https://fluxui.dev/docs/installation
> Supports Laravel 10

- src/Console/PublishCommand.php
If you try to publish a button or tooltip, you get an exception. I don't know if they are meant to be free or pro, so I just commented out the option for now.
```
UnhandledMatchError 
Unhandled match case true  at /Users/eserdeniz/Projects/fork-flux/src/Console/PublishCommand.php:135
```
> Fix publish command

- src/FluxManager.php
This PR fixes the spelling of the method "disallowWireModel"
The method is not called anywhere in the this repo, so the changes will most likely affect the pro package, not available yet.
Possibly also the documentation.
I have purchased a license, and once the other repos become available to me, I'll gladly send matching PRs there as well.
> Fix spelling

- stubs/resources/views/flux/button/index.blade.php
Currently if you have a standard button and a link button, the standard button will be small but the link button will expand to fill all available space (see first screenshot below).
```blade
<flux:button>Test</flux:button>
<flux:button href="/">Test</flux:button>
```
**Before - button inline-block, link acting like a block**
The reason for this is buttons are `display:inline-block` by default where as links are `display:block`.
So instead of using `flex` on the button component, we should use `inline-flex`. This PR makes that change (see second screenshot below).
**After - both acting like inline block**
Fixes #28.
> Ensure button and link button display the same

- stubs/resources/views/flux/button-or-link.blade.php
Currently the `button-or-link` component doesn't recognise URLs generated using the `route()` helper as being the current route.
So this won't have the current page highlighting:
```blade
<flux:navlist.item href="{{ route('news') }}">Latest News</flux:navlist.item>
```
This PR fixes that.
Fixes #23
> Fix link current check to strip the app url

- src/Console/PublishCommand.php
Currently, the `navmenu` components aren't published when publishing the dropdown.
Fixes #29
> Fix publishing navmenu components

- stubs/resources/views/flux/button-or-link.blade.php
Follow up from PR #26 which fixed links to allow `route()` helper to be passed in as an href.
There is now an issue where some URLs have an extra trailing slash added by mistake. `https://myproject.com/some/route?parameter=value/`
This PR fixes that.
I have manually tested to make sure that the following render correctly:
- `/`
- `app.test`
- `app.test/`
- `route('home')`
- `/some-other-route?with-query=params`
Fixes #67
Fixes #93
> Fix link href extra trailing slash

- composer.json
Also see pull request [48](https://github.com/livewire/flux/pull/48). New Laravel installation (Laravel Framework v11.24.1, no starter kit).
```
Problem 1
- livewire/flux v1.0.0 requires laravel/prompts ^0.1.24 -> found laravel/prompts[v0.1.24, v0.1.25] but the package is fixed to v0.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- livewire/flux v1.0.1 requires laravel/prompts ^0.1 -> found laravel/prompts[v0.1.0, ..., v0.1.25] but the package is fixed to v0.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```
> Laravel Prompts (composer.json)

- stubs/resources/views/flux/menu/item.blade.php
Removed an extra double quote in the flux:menu.item component on Line 45. 
This resolves issue #121 , which was causing syntax errors in the component.
> Fix extra double quote in flux.menu.item component #121

- stubs/resources/views/flux/button-or-link.blade.php
Original issue: https://github.com/livewire/flux/issues/162
This PR allows the use of `current` on a navlist button that triggers a dropdown:
```html
<flux:navbar>
<flux:dropdown>
<flux:navbar.item icon-trailing="chevron-down" current>Account</flux:navbar.item>
<flux:navmenu>
{{-- ... --}}
</flux:navmenu>
</flux:dropdown>
</flux:navbar>
```
> Allow "current" prop on navlist items

- stubs/resources/views/flux/button/group.blade.php
- stubs/resources/views/flux/button/index.blade.php
We did a deep dive and made sure all button and input variants and combinations look good inside groups:
> Fix button and input group styling

- src/Console/PublishCommand.php
Currently when `flux:publish` is run, the table folder is being published, but the table blade file isn't.
It is because in Flux Pro there is both a `table` folder and a `table.blade.php` file and the publish command doesn't support matching both.
This PR fixes the publish command to check for a directory and also for a file.
Fixes https://github.com/livewire/flux/issues/316
> Fix publish command to include table

- src/Console/PublishCommand.php
Introduced a --force option to the PublishCommand to override existing files and directories.
This enhancement allows users to forcefully publish components even if they already exist.
Updated the logic to check this new option before skipping existing paths.
> Add --force option to PublishCommand

- src/FluxTagCompiler.php
this update replaces the use of `$attributes->all()` with `$attributes->getAttributes()` to fix the breaking change from #620
> Update FluxTagCompiler.php to fix #620

- .github/ISSUE_TEMPLATE/bug_report.yml
This PR adds an issue form template instead of just the single text box to add more structure for people reporting issues.
> Add issue form template

- src/AssetManager.php
- src/FluxManager.php
This PR introduces the ability to optionally specify a Content Security Policy (CSP) nonce for the script and style assets injected via the custom Blade directives (`@fluxStyles` and `@fluxScripts`). This is necessary for those using stricter CSP headers in their projects, and I've followed the same implementation as seen in the Livewire package.
Simple pass the `nonce` value in an array to the Flux Blade directives:
```
@fluxStyles(['nonce' => 'abcdef'])
```
and
```
@fluxScripts(['nonce' => 'abcdef'])
```
The nonce value will be included in the relevant assets:
```
<link rel="stylesheet" href="/flux/flux.css?id=0e2b9c8b" nonce="abcdef">
```
and
```
<script src="/flux/flux.js?id=4c114991" data-navigate-once nonce="abcdef"></script>
```
> Add optional CSP nonce support for Flux script and style directives

- stubs/resources/views/flux/button/index.blade.php
Currently if you have a table each with an action like `delete($userId);` all the delete buttons will show a loading indicator at the same time.
This is because under the hood, Livewire scopes the buttons loading state to the action called in the `wire:click` but it doesn't take into account any parameters.
This PR adds `wire:target` including parameters to buttons if there isn't already a `wire:target` and it's not a submit button.
> Add `wire:target` to buttons with parameters included

- stubs/resources/views/flux/tooltip/index.blade.php
This PR adds a `toggleable` prop to the `<flux:tooltip>` component.
```blade
<flux:tooltip content="Information" toggleable>
<flux:button icon="information-circle" icon-variant="outline" />
</flux:tooltip>
```
This allows a tooltip to be shown/hidden by a button click/press, instead of on hover/focus as they don't work on mobile.
It's good for creating information "i" buttons next to elements, to add some helpful information.
See https://github.com/livewire/flux/issues/682#issuecomment-2544689857 for more details on tooltips and mobile compatibility.
I've also submitted a PR to the Flux docs.
Fixes #682
> Add `toggleable` prop to tooltip

- src/AssetManager.php
Correctly render the stylesheet so that the $versionHash and $nonce values actually appear instead of just showing the PHP variables.
Fixes #932
> Fix `@fluxStyles` rendering

- stubs/resources/views/flux/button/index.blade.php
If you use buttons with `icon-variant="outline"` the icons are bigger than the default solid sizes.
```blade
<flux:button
variant="outline"
icon="bolt"
icon-trailing="academic-cap"
icon-variant="outline">
Outline
</flux:button>
<flux:button
variant="outline"
icon="bolt"
icon-trailing="academic-cap">
Solid
</flux:button>
```
And the same issue happens with square buttons.
The issue is that outline icons have a 24x24 view box and there isn't a smaller outline variant. Where as for buttons the default icon variant is micro which has a view box of 16x16.
This PR resizes the outline icon variant to be the same size as the default button icon sizes, using `size-4` by default.
If the `square` button attribute is used, then the size is set to `size-5`.
It's not an ideal solution as the size of …
> Fix outline icon sizes on buttons to ensure they match default icon sizes

- src/AssetManager.php
This addresses #998 .
**Before**: `php artisan route:cache` serializes through reflection the route callbacks, hardwiring the execution context's absolute path to flux's asset files (ex: /Users/vorban/repositories/...) because of `__DIR__` resolution.
**After**: `php artisan route:cache` serializes references to the route actions, preventing any resolution of `__DIR__` before runtime.
I've tested it locally. The routes are listed by `artisan route:list`, and `artisan route:cache` correctly serialized references to the functions.
After a `route:cache`, going to any page that uses the blade directives like `@fluxStyles` works and the files are correctly fetched.
I'd prefer this to be thoroughly reviewed, as I failed to find the contribution guidelines and test suites to run.
> Fix asset route caching

- stubs/resources/views/flux/dropdown.blade.php
- stubs/resources/views/flux/tooltip/index.blade.php
This is a follow up from PR livewire/flux-pro#142 "Add `.self` to `wire:model` on a modal automatically".
In this PR we also automatically add `.self` to other components that are wrapping components like a modal is.
See PR description copied to the original issue here for details https://github.com/livewire/flux/issues/850#issuecomment-2576895754
This PR adds `.self` check to the following components:
- dropdown
- tooltip
There is also a companion PR livewire/flux-pro#154 on the Flux Pro repo which adds `.self` check to the following components:
- accordion
- context
> Add `.self` to `wire:model` on wrapper components

- stubs/resources/views/flux/menu/item.blade.php
This is a follow up from PR livewire/flux#987 "Fix outline icon sizes on buttons to ensure they match default icon sizes".
In this PR we also fix any other components that accept the `icon` prop to match outline icon sizes to the default icon sizes.
There were some components that didn't not accept a `icon-variant` prop, so these have been added.
There is also a companion PR livewire/flux-pro#155 on the Flux Pro repo.
> Add icon variant and fix outline icon sizes

- stubs/resources/views/flux/menu/checkbox/index.blade.php
- stubs/resources/views/flux/menu/item.blade.php
- stubs/resources/views/flux/menu/radio/index.blade.php
- stubs/resources/views/flux/menu/submenu.blade.php
- stubs/resources/views/flux/navmenu/item.blade.php
In Flux some components support passing in icon names.
```blade
<flux:button icon="arrow-down-tray">Export</flux:button>
```
Or using icon as a slot.
```blade
<flux:button>
<x-slot:icon>
<flux:icon.arrow-down-tray />
</x-slot>
Export
</flux:button>
```
But there are some components that don't support this and only support passing the name of an icon in.
This PR and a companion Flux Pro PR livewire/flux-pro#173 fixes this by updating all components that support icons to have icon slots as well.
Some components that are similar, like some of the menu components, may have supported trailing icons and others not, so support has also been added so this is consistent with components that as used similarly.
> Fix component icons to also support slots

- src/AssetManager.php
If you have a strict CSP setup, an error is being thrown because of Flux's dark mode detection script that gets injected with the styles.
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-pUT16AksAMo5zjRjbkiC8r9adYK9uLENJMpcYSZD' https://www.googletagmanager.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-10Dh1l13zor4I3gkPqw4Y1m3FpiMnB1VtjcVaCLTYFg='), or a nonce ('nonce-...') is required to enable inline execution.
```
The issue is that Flux's styles and scripts both support a nonce but the new inline dark mode script does not.
The solution is to add the nonce that can be passed into `@fluxStyles(['nonce' => 'abc'])` to the inline script.
Fixes #1034
> Add nonce to dark mode script tag

- stubs/resources/views/flux/checkbox/group/variants/default.blade.php
Currently if you have any inputs inside a checkbox group with `wire:model` on it (such as a table wrapped with checkbox.group for check all functionality), then typing in one of the inputs changes the checkbox group `wire:model` value.
<details>
<summary>Volt component</summary>
```blade
<?php
use Flux\DateRange;
use Livewire\Attributes\Computed;
use \Livewire\WithPagination;
public $selectedUsers = [];
public $sortBy = 'date';
public $sortDirection = 'desc';
public function sort($column) {
if ($this->sortBy === $column) {
$this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
} else {
$this->sortBy = $column;
$this->sortDirection = 'asc';
}
}
#[\Livewire\Attributes\Computed]
public function users()
{
return …
```
> Add `.self` to `wire:model` on `checkbox.group` component

- stubs/resources/views/flux/input/file.blade.php
Currently if you add a `name` attribute to a file input it's being incorrectly escaped.
```blade
<flux:input type="file" name="my-file" />
```
The issue is that in the code, the `{{ }}` is escaping everything including the quotes.
```blade
{{ $name ? 'name="'.$name.'"' : '' }}
```
The solution is to switch to using a blade conditional instead
```blade
@if($name)name="{{ $name }}"@endif
```
Fixes livewire/flux#1063
> Fix file input name being escaped

- stubs/resources/views/flux/checkbox/index.blade.php
- stubs/resources/views/flux/radio/index.blade.php
If you have a checkbox or radio button wrapped in another element that sets a variant like a modal with a flyout variant, the checkbox/ radio were incorrectly trying to use that variant type.
```blade
<flux:modal variant="flyout">
<flux:checkbox label="Email" />
</flux:modal>
```
The issue is that the `@aware('variant')` inside checkboxes/ radios is pulling the variant from the modal component, causing an invalid variant.
The solution is to add a check to make sure the variant exists for the checkbox/radio and if it doesn't then just fall back to using the default instead of throwing an error.
Fixes #1106, fixes #1108, fixes #1116, fixes #1121
> Fix checkbox and radio wrapping element variant does not exist error

- stubs/resources/views/flux/select/variants/default.blade.php
If you use the select default variant in dark mode on windows, the background of the select is not dark and the contrast makes it hard to read.
```blade
<flux:select wire:model="industry" placeholder="Choose industry...">
<flux:select.option>Photography</flux:select.option>
<flux:select.option>Design services</flux:select.option>
<flux:select.option>Web development</flux:select.option>
<flux:select.option>Accounting</flux:select.option>
<flux:select.option>Legal services</flux:select.option>
<flux:select.option>Consulting</flux:select.option>
<flux:select.option>Other</flux:select.option>
</flux:select>
```
The issue is that the native select dropdown doesn't seem to allow background styles to be applied directly to it. Filament has run into this issue before too …
> Fix select default variant background not dark in dark mode on Windows

- src/FluxManager.php
- src/FluxTagCompiler.php
Current components that use the Flux delegate component to dynamically load components, like icons, aren't loading on Laravel 12.
The issue is that in Laravel 12 the Blade compiler's anonymous component path has been updated to use a faster hashing algorithm instead of md5 https://github.com/laravel/framework/pull/52301.
The solution is we need to update Flux's component checks and delegate component generation to detect whether Laravel 12 or newer is being used and use the new hashing algorithm if so.
> Fix anonymous component views for Laravel 12

- stubs/resources/views/flux/button-or-div.blade.php
Currently if you want to use a badge as a submit button, the button's type is set to `button` even if you pass in `type="submit"`.
```blade
<flux:badge color="cyan" as="button" type="submit">Submit button</flux:badge>
```
The badge component is wrapped in the `button-or-div` component and the attributes are being correctly forwarded to it.
But it turns out that the type on the button in the `button-or-div` component is hard coded, so can't be overridden with attributes.
```blade
<button type="button" {{ $attributes }}>
```
Change `button-or-div` button so that the type can be merged in through attributes.
```blade
<button {{ $attributes->merge(['type' => 'button']) }}>
```
> Fix button-or-div to allow button type to be changed

- stubs/resources/views/flux/input/clearable.blade.php
If you have a date pciker with an input that has the `clearable` attribute, currently pressing the clear button will clear the input value but won't update the value stored by Livewire.
```blade
<?php
public $date;
};
?>
<div>
<flux:text>Date: {{ $date }}</flux:text>
<flux:date-picker
wire:model.live="date"
>
<x-slot name="trigger">
<flux:date-picker.input clearable />
</x-slot>
</flux:date-picker>
</div>
```
The problem is that the clear button only dispatches an input event but the date picker is listening for a change event on the input.
The solution is to update the clearable button to also dispatch a change event, which I have done in this PR. I also refactored the clear button to make it more efficient and readable.
Fixes …
> Fix input clearable button to also dispatch change event

- stubs/resources/views/flux/input/clearable.blade.php
This PR adds a `data-flux-clear-button` attribute to the input clear button so it can be identified by the date picker and filtered out so it doesn't become a trigger button. See livewire/flux-pro#196 for details.
> Add `data-flux-clear-button` to the clear button

- src/DateRangeSynth.php
If a Livewire property is set to a DateRange with a preset of AllTime, then on the next request it fails to hydrate and throws the following error:
```blade
<?php
use Flux\DateRange;
public DateRange $range;
public function mount(): void
{
$this->range = DateRange::allTime('2018-01-01');
}
}; ?>
<div class="flex">
<flux:date-picker wire:model.live="range" mode="range" min="2018-01-01" with-presets/>
</div>
```
The issue is that we're not handling the AllTime preset in the hydrate method of `DateRangeSynth`.
```php
if ($preset) {
return DateRange::fromPreset(DateRangePreset::from($preset));
}
```
This PR adds a check for AllTime and handles it the same way that the `hydrateType` method does.
```php
if ($preset) {
if ($preset === …
```
> Fix DateRangeSynth hydrate of all time preset

- src/DateRange.php
We have documented that a `isNotAllTime()` method exists on the `DateRange` object, but it doesn't actually exist.
https://fluxui.dev/components/date-picker#all-time
> If you are using this date range to filter data, you may want to remove "where" constraints from the query when allTime is selected:
>
> ```php
> <?php
> 
> $orders = Order::when($this->range->isNotAllTime(), function ($query) => {
>     $query->whereBetween('created_at', $this->range);
> })->get();
> ```
This PR adds it.
```php
public function isNotAllTime(): bool
{
return $this->preset !== DateRangePreset::AllTime;
}
```
Fixes livewire/flux#1164
> Add missing `isNotAllTime()` method to DateRange

- stubs/resources/views/flux/switch.blade.php
Currently if you want to left-align a switch, you can't use the `label` short hand and instead you need to use the `flux:field` component and syntax.
```blade
<flux:fieldset>
<flux:legend>Email notifications</flux:legend>
<div class="space-y-3">
<flux:field variant="inline" class="w-full flex justify-between">
<flux:switch wire:model.live="email" />
<flux:label>Communication emails</flux:label>
<flux:error name="email" />
</flux:field>
<flux:field variant="inline" class="w-full flex justify-between">
<flux:switch wire:model.live="marketing" />
<flux:label>Marketing emails</flux:label>
<flux:error name="marketing" />
</flux:field>
<flux:field variant="inline" class="w-full flex justify-between">
<flux:switch wire:model.live="social" />
<flux:label>Social emails</flux:label>
<flux:error …
```
> Add switch `left-align` attribute

- src/FluxManager.php
- src/FluxTagCompiler.php
This is a backport of PR #1141 to Flux v1 to fix anonymous component views in Laravel 12.
Fixes livewire/flux#1192
> [1.x] Fix anonymous component views for Laravel 12

- stubs/resources/views/flux/select/variants/default.blade.php
Currently if you have inputs, date pickers and selects together in the same form, they are displaying different text sizes
**Mobile before**
**Desktop before**
```blade
<?php
//
}; ?>
<div class="flex flex-col gap-2">
<flux:input label="Input" value="5 Feb 2025" />
<flux:date-picker label="Date picker" value="2025-02-05"/>
<flux:date-picker value="2025-02-05">
<x-slot name="trigger">
<flux:date-picker.input />
</x-slot>
</flux:date-picker>
<flux:select label="Select">
<flux:select.option selected>5 Feb 2025</flux:select.option>
</flux:select>
<flux:select variant="listbox" label="Listbox">
<flux:select.option selected>5 Feb 2025</flux:select.option>
</flux:select>
<flux:select variant="combobox" label="Combobox">
<x-slot …
```
> Fix select sizes to match other inputs

- stubs/resources/views/flux/button/index.blade.php
I just changed the conditional that sets the $isJsMethod value to use an empty string in cases where there isn't a wire:click attribute passed to the button component.
It may not be the best solution; I haven't really looked at the rest of the codebase. A user in the Livewire Discord posted that he'd received these notices, and I'm assuming it's from Flux.
Discord Details:
[Original Message ](https://discord.com/channels/698229985755791471/698229986233942028/1344385903233335390)
> Fix deprecation warning when button has missing wire:click

- stubs/resources/views/flux/select/option/index.blade.php
If you use a default select inside a component that has a variant defined, like a modal, then the select options aren't showing up.
```blade
<?php
//
}; ?>
<div>
<flux:modal.trigger name="edit-profile">
<flux:button>Edit profile</flux:button>
</flux:modal.trigger>
<flux:modal variant="flyout" name="edit-profile" class="md:w-96">
<flux:select placeholder="Choose industry...">
<flux:select.option>Photography</flux:select.option>
<flux:select.option>Design services</flux:select.option>
<flux:select.option>Web development</flux:select.option>
<flux:select.option>Accounting</flux:select.option>
<flux:select.option>Legal services</flux:select.option>
<flux:select.option>Consulting</flux:select.option> …
```
> Fix select option variant not found

- stubs/resources/views/flux/switch.blade.php
I have a switch toggle placed within a flex and justify-between element, which get's truncated and looks like this:
The only fix I found so far is to replace the fixed width with a min width, so instead of w-8 we take min-w-8, and voila, it works:
For clarification, my blade template is this:
```blade
<div class="flex items-start gap-4 justify-between">
<flux:heading>{{ __('Get email notifications about new subscribers') }}</flux:heading>
<flux:switch wire:model.live="state.notify_about_new_subscriber" class="cursor-pointer"/>
</div>
```
> Switch Toggle: Replace w-8 with min-w-8 to fix parent's flex issues

- stubs/resources/views/flux/modal/trigger.blade.php
Currently if you use the command palette in a modal on Firefox and try to open the command palette using the `cmd+k` modal trigger shortcut, those command palette opens but so does Firefox's address bar.
```blade
<?php
//
}; ?>
<div>
<flux:modal.trigger name="search" shortcut="cmd.k">
<flux:input as="button" placeholder="Search..." icon="magnifying-glass" kbd="⌘K" />
</flux:modal.trigger>
<flux:modal name="search" variant="bare" class="w-full max-w-[30rem] my-[12vh] max-h-screen overflow-y-hidden">
<flux:command class="border-none shadow-lg inline-flex flex-col max-h-[76vh]">
<flux:command.input placeholder="Search..." closable />
<flux:command.items>
<flux:command.item icon="user-plus" kbd="⌘A">Assign to…</flux:command.item> …
```
> Fix modal trigger on Firefox

- stubs/resources/views/flux/label.blade.php
Currently if you use normal badges near label badges, they look different. The label badges also can't make use of the different badge colours.
```blade
<?php
//
}; ?>
<div>
<flux:badge size="sm">Badge</flux:badge>
<flux:field>
<flux:label badge="Required">Email</flux:label>
<flux:input type="email" required />
</flux:field>
</div>
```
The issue is that the label badge isn't using the badge component as it was designed to be something slightly different.
The solution is to make the label badge slotable, that way if a user needs an actual badge there whether for design reasons or colour reasons, they can do so.
```blade
<flux:label>
<x-slot:badge>
<flux:badge size="sm">Required</flux:badge>
</x-slot:badge>
Email
</flux:label>
``` …
> Make label badge slottable

- stubs/resources/views/flux/input/clearable.blade.php
- stubs/resources/views/flux/input/copyable.blade.php
- stubs/resources/views/flux/input/expandable.blade.php
- stubs/resources/views/flux/input/index.blade.php
- stubs/resources/views/flux/input/viewable.blade.php
Currently if you try to use `copyable`, `viewable`, or `expandable` on inputs that are size `xs` then the overstate overlaps and the icon sizes aren't great. But if you try to use `clearable` on an `xs` input, then it doesn't show at all.
```blade
<div class="space-y-4">
<flux:input size="xs" clearable />
<flux:input size="xs" copyable />
<flux:input size="xs" viewable />
<flux:input size="xs" expandable />
</div>
```
The issue with the first 3 options is that when looking in the copyable/expandable/viewable components, they have support for size `sm` but not size `xs` which is causing the larger buttons and icons to be shown.
```blade
<flux:button
:size="$size === 'sm' ? 'xs' : 'sm'"
...
>
```
Where as the clearable component won't even render at all, because the `input/index.blade.php` …
> Fix `-able` buttons on xs inputs

- stubs/resources/views/flux/error.blade.php
While this PR doesn't actually depend on PR #1295, I have branched this PR off that one to make testing easier, so I would recommend merging that PR first before reviewing this one. 
Currently if we have a component, like the date picker, that updates a property which has nested attributes, then the validation errors for those nested attributes aren't shown.
For example, if we have a date range picker and we have rules for start and end to ensure that start is before end, then if a range is submitted the wrong way around and validation fails, no error messages are show for `range.start` or `range.end`.
```blade
<?php
use App\Rules\DateRangeRule;
use Flux\DateRange;
use Flux\DateRangePreset;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Validate; …
```
> Update error component to support nested attributes

- stubs/resources/views/flux/badge/index.blade.php
Currently if you have a badge with `inset` or `inset="left"` it's not inset fully. As you can see in the image below, the badge text is slightly to the right of the heading text.
<div>
<flux:badge inset="left">Badge</flux:badge>
<flux:heading>Heading</flux:heading>
</div>
The issue is that the badge has a `px-2` on it, and the inset for right is set to `-mr-2` but left is set to `-ml-1`.
This PR updates the left inset to be `-ml-2` to match the padding.
Fixes livewire/flux#1294
> Fix badge left inset

- stubs/resources/views/flux/label.blade.php
Currently you cannot select the text of an input label, which is different to how the native browser label works.
You can see in the screencapture below, that a browser label has a default cursor but the text is selectable, where as the Flux label has a default cursor but the text is not selectable (for some reason the cursor didn't move in the screencapture, but rest assured that it did). This is inconsistent.
```blade
<div>
<flux:input label="Flux Label" />
<label for="testing">Browser Label</label>
<input type="text" id="testing" class="block border" />
</div>
```
The issue is that the label component has `select-none` class on it and the label javascript is injecting `user-select: none`.
```js
inject(({ css }) => css`
ui-label { display: inline-block; cursor: default; user-select: …
```
> Fix label so it's selectable

- src/DateRangeSynth.php
- stubs/resources/views/flux/error.blade.php
Note: This PR depends on this Livewire PR [Add validation support to synths](https://github.com/livewire/livewire/pull/9231#top) being merged and tagged first.
Currently if we have a date range picker that is bound to a property of type `DateRange`, there is no way to validate that the start, end, and preset properties on the `DateRange` object are valid.
For a full write up of this issue, please read this comment https://github.com/livewire/flux/issues/1222#issuecomment-2712542844
The issue is that Livewire has no way of knowing how to format a `DateRange` object in a way where Laravel's validation can process the properties on the `DateRange` object.
I go into detail in the issue comment https://github.com/livewire/flux/issues/1222#issuecomment-2712542844 and the Livewire PR …
> Fix `DateRangeSynth` so the `DateRange` can be validated

- src/Console/PublishCommand.php
Currently brand and avatar cannot be published.
The issue is that brand isn't listed in the publish command and avatar was still under table in the Pro section, but it's now standalone and should be free.
Added brand and avatar, each as their own options to publish under the free components. And removed avatar from under table in the pro components.
Fixes livewire/flux#1311
> Add missing components to publish command

- stubs/resources/views/flux/error.blade.php
With the recent changes to error component to support nesting #1308, occasionally there can be an issue if `$errors->first()` is called in a test, as it throws an `Undefined variable $errors` error. This recently caused a breaking change for someone.
The issue is actually an underlying Laravel issue where for some reason if a view is manually rendered in a test, it has no idea that the `$errors` variable should exist and throws an error. https://laracasts.com/discuss/channels/testing/undefined-variable-errors-when-testing-a-view
By itself, this shouldn't cause issues for us, but with the recent change to the errors component, this error is now being throws in a users app.
The reason why it wasn't being thrown before, is because we only had the below code.
```php
$message ??= $name ? …
```
> Fix error component by adding name check

- stubs/resources/views/flux/input/index.blade.php
Currently if an input is used for search or something like that, there is no easy way to get the trailing icon to display a spinner when a Livewire request is happening.
```blade
<flux:input wire:model.live="search" icon-trailing="loading" placeholder="Search transactions" />
```
Instead you have to use slots.
```blade
<flux:input wire:model.live="search" placeholder="Search transactions">
<x-slot:trailing-icon>
<flux:icon.loading wire:loading wire:target="search" />
</x-slot>
</flux:input>
```
This PR adds support for the following API mapped out by @calebporzio here https://github.com/livewire/flux/issues/1286#issuecomment-2719092938.
```blade
<flux:input wire:model="search" />{{-- no loading indicator ever --}}
<flux:input wire:model.live="search" />{{-- loading indicator when request …
```
> Add loading support to inputs

- src/FluxManager.php
Updated FluxManager line 127 to use `->getAttributes()` on the `ComponentAttributeBag` rather than `->all()` to be compatible with Laravel 10.
Fixes livewire/flux#1385
Similar to livewire/flux#621
> Updates FluxManager to be compatible with Laravel 10

- stubs/resources/views/flux/avatar/index.blade.php
Currently if you try to use the avatar component with a name that starts with a number or is incorrectly formatted (like it has leading spaces or something), then the avatar component throws the below error.
```blade
<div> 
<flux:avatar name="3M"/>
<flux:avatar name=" bob smith"/>
</div>
```
The issue is that the regex doesn't account for names that can start with digits,  like a company name such as 3M, and it also doesn't factor in leading white space, if data is incorrectly formatted.
```php
$parts = explode(' ', preg_replace('/[^a-zA-Z\s]/', '', $name));
```
To fix this, I've updated the regex to allow digits and also added a `trim()` to the `$name`.
```php
$parts = explode(' ', preg_replace('/[^a-zA-Z0-9\s]/', '', trim($name)));
```
Fixes livewire/flux#1387
> Fix avatar initials edge cases

- stubs/resources/views/flux/callout/heading.blade.php
- stubs/resources/views/flux/callout/index.blade.php
Currently if you have a coloured callout that has an action button with an icon, the action button icon colour is being changed to the colour of the other icons in the callout.
```blade
<div> 
<flux:callout icon="information-circle" color="amber" inline>
<flux:callout.text>There is an issue with your provider account. </flux:callout.text>
<x-slot name="actions">
<flux:button icon="wrench">Repair</flux:button>
</x-slot>
</flux:callout>
<flux:callout color="amber">
<flux:callout.heading icon="newspaper">Policy update</flux:callout.heading>
<flux:callout.text>We've updated our Terms of Service and Privacy Policy. Please review them to stay informed.</flux:callout.text>
<x-slot name="actions">
<flux:button icon="wrench">Repair</flux:button>
</x-slot>
</flux:callout>
</div>
```
The issue is …
> Fix callout action button icon colours

- dist/flux.css
- stubs/resources/views/flux/modal/index.blade.php
This has a corresponding Flux Pro PR livewire/flux-pro#234
Currently if you open a flyout modal on Safari, the flyout initially appears on the left, and then jumps to the right instead of animating in. The same issue is also happening with toasts.
```blade
<div> 
<flux:modal.trigger name="edit-profile">
<flux:button>Edit profile</flux:button>
</flux:modal.trigger>
<flux:modal name="edit-profile" variant="flyout">
<div class="space-y-6">
<div>
<flux:heading size="lg">Update profile</flux:heading>
<flux:text class="mt-2">Make changes to your personal details.</flux:text>
</div>
<flux:input label="Name" placeholder="Your name" />
<flux:input label="Date of birth" type="date" />
<div class="flex">
<flux:spacer />
<flux:button type="submit" variant="primary">Save changes</flux:button>
</div> …
```
> Fix flyout modal and toasts display bug

- stubs/resources/views/flux/with-field.blade.php
Currently if you have a input that has a label using the short hand syntax, if you try to add margin top to that component `class="mt-6"`, it actually puts the margin between the label and the input instead of above the input which is what is intended.
```blade
<div>
<flux:heading size="xl">Profile</flux:heading>
<flux:input class="mt-6" label="Name" />
</div>
```
The issue is that any classes that are passed into the input component are being applied to the input components itself and not the wrapping field/label component.
The input component at the moment is structured like this (simplified for demonstration purposes)
```blade
<flux:with-field :$attributes :$name>
<div {{ $attributes->only('class') }}>
<input
type="{{ $type }}"
{{ $attributes->except('class')->class($classes) }}
> …
```
> Enable scoped attributes for field components

- stubs/resources/views/flux/with-field.blade.php
- stubs/resources/views/flux/with-inline-field.blade.php
Currently if you have a label that is `"0"` then it's not being rendered when used with any inline or normal inputs.
```blade
<div>
<flux:radio.group>
@foreach (['0', '1', '-1', '∞'] as $option)
<flux:radio :label="$option" :value="$option" />
@endforeach
</flux:radio.group>
</div>
```
The issue is that the `with-field` and `with-inline-field` wrapper component's have a `if ($label)` check which returns false for falsey values like `0`.
This PR updates them to use `isset($label)` to ensure all values are rendered as expected. I also updated `$description` to be the same.
Now the `"0"` label is rendering as expected.
Fixes livewire/flux#1454
> Fix label and description falsey check

- stubs/resources/views/flux/avatar/index.blade.php
Currently if the avatar component is passed a name that isn't in a specific format, it can cause a few different errors to be thrown depending on the contents:
Things like a name with unicode characters, a name with only a single letter, and name with a last name that is a single letter, etc.
```blade
<div>
<flux:avatar name="" initials:single/>
<flux:avatar name="Caleb Porzio" initials:single/>
<flux:avatar name="Админ" initials:single/>
<flux:avatar name="" />
<flux:avatar name="Caleb" />
<flux:avatar name="Админ" />
<flux:avatar name="C" />
<flux:avatar name="Caleb P" />
<flux:avatar name="Caleb Porzio" />
<flux:avatar initials="CP" />
<flux:avatar icon="key" />
</div>
```
The issue is that there are a bunch of arrays being accessed without any checks to ensure the array keys exist. …
> Fix avatar component

- stubs/resources/views/flux/modal/index.blade.php
This PR has a supplementary Flux Pro PR livewire/flux-pro#242.
The main fix is in the Flux Pro PR, so I recommend checking that out first.
Currently, if you have a modal which has an input, that input is being focused when the modal is opened.
This is causing issues for screen readers as the screen reader is also being focused at the input and any heading/ text gets skipped.
This also causes issues for mobile users as by focusing the input, the keyboard is shown which takes up half of the screen hiding some of the contents of the modal.
```blade
<?php
public $show = false;
}; ?>
<div>
<flux:modal.trigger name="edit-profile">
<flux:button>Edit profile</flux:button>
</flux:modal.trigger>
<flux:modal wire:model="show" …
```
> Fix modal autofocus issue

- stubs/resources/views/flux/avatar/index.blade.php
Currently if you use avatar inside a flexbox and one of the other elements tries to take up extra space, the avatar background circle gets all squished up.
```blade
<?php
//
};
?>
<div class="flex w-full items-center gap-4">
<flux:avatar circle src="https://unavatar.io/x/calebporzio" />
<div class="w-full">
<p class="font-bold">Caleb Porzio</p>
<p>commented</p>
</div>
</div>
```
The issue is that the avatar element is being squished by the flexbox, but the img is still being shown as a perfect circle, which is causing the background circle to be pushed out of shape.
The solution is to add `flex-none` to the avatar component, which stops it from being squished by the flexbox.
Fixes livewire/flux#1532
> Fix avatar in a flexbox

- stubs/resources/views/flux/select/variants/default.blade.php
Currently if you have a default select and have selected a option that has a letter that hangs down, like `g` or `y`, then the bottom of the letter is being cut off.
```blade
<flux:select wire:model="industry" placeholder="Choose industry...">
<flux:select.option>Photography</flux:select.option>
<flux:select.option>Design services</flux:select.option>
<flux:select.option>Web development</flux:select.option>
<flux:select.option>Accounting</flux:select.option>
<flux:select.option>Legal services</flux:select.option>
<flux:select.option>Consulting</flux:select.option>
<flux:select.option>Other</flux:select.option>
</flux:select>
```
The issue is that the line height is set to `leading-none` for the default select, which is causing the descenders to be cut off.
```php
->add(match ($size) { …
```
> Fix default select line height

- stubs/resources/views/flux/select/variants/default.blade.php
Currently if you have a default select and it's disabled it doesn't look disabled.
**Light mode disabled**
**Dark mode disabled**
```blade
<div>
<flux:input label="Input" value="Test" disabled />
<flux:select label="Default Select" disabled>
<flux:select.option selected>Test</flux:select.option>
</flux:select>
<flux:select label="Listbox" variant="listbox" disabled>
<flux:select.option selected>Test</flux:select.option>
</flux:select>
</div>
```
The issue is that there are no disabled text styles for the default select. I also noticed that when default select is disabled in dark mode, it's background colour is slightly different to the input and listbox select.
The solution is to add disabled text colours for light and dark mode to match inputs/ listboxes and fix the dark disabled …
> Fix default select disabled and dark styles

- stubs/resources/views/flux/select/option/index.blade.php
Currently if you have a `<flux:select.option>` and you put a `label` attribute on it, it renders the option with a label which is incorrect.
```blade
<?php
use Livewire\Attributes\On;
//
}; ?>
<div>
<flux:select variant="combobox">
<flux:select.option label="John Smith">
John Smith <span class="ml-1 text-gray-500">Smith Constructions</span>
</flux:select.option>
<flux:select.option label="Bob Jane">
Bob Jane <span class="ml-1 text-gray-500">Bob's Tyres</span>
</flux:select.option>
<flux:select.option label="John Doe">
John Doe <span class="ml-1 text-gray-500">Doe's Plumbing</span>
</flux:select.option>
</flux:select>
</div>
```
The issue is that `select/option/index.blade.php` is a component which delegates to other option …
> Fix select option

- stubs/resources/views/flux/button/index.blade.php
This PR adds support for adding a `color` prop to the `button` element for primary buttons. This will only work for buttons with `variant="primary"` as they are the ones that use accent colours.
```blade
<div>
<flux:button variant="primary" color="blue">Primary</flux:button>
<flux:button variant="primary" color="yellow">Primary</flux:button>
<flux:button variant="primary" color="green">Primary</flux:button>
</div>
```
> Add color prop for primary buttons

- stubs/resources/views/flux/label.blade.php
There is a misalignment when using `<flux:label>` with a badge
Simply adding inset top bottom, `-mb-1 -mt-1` fixes the problem
```blade
<div class="space-y-6 md:space-y-0 md:grid grid-cols-2 gap-4">
<flux:input label="Email" type="email"/>
<flux:input badge="Optional" label="Phone" type="phone"/>
</div>
```
> Fix misalignment when using badge in flux:label

- stubs/resources/views/flux/navlist/group.blade.php
Currently if you are using the navlist group on an RTL site, the closed chevron is still pointing right instead of left.
The issue is we have no handling for RTL in the navlist group component, so it needs to be added.
The solution is to ensure we rotate the chevron to the left instead of the right when RTL is enabled.
I've done this by adding `rtl:rotate-180` to the icon.
Fixes livewire/flux#1691
> Fix RTL navlist group closed chevron

- stubs/resources/views/flux/button/index.blade.php
This PR fixed a visual issue with the button padding if the button is type submit.
```html
<flux:button variant="primary">Save</flux:button>
```
```html
<flux:button variant="primary" type="submit">Save</flux:button>
```
As you can see the left padding is smaller if the button is type submit, so the text is not centered.
Fixes #1728
> Fixed button padding

- stubs/resources/views/flux/profile.blade.php
Currently if you pass a name like "Caleb" to the avatar component, it will generate initials "Ca", but if you do the same for the profile component it generates initials "C".
```blade
<div>
<flux:profile name="Caleb" />
<flux:avatar name="Caleb" />
</div>
```
The issue is that there is an inconsistency between how the initials are generated because the profile component has it's own initials generation logic which is different to the avatar logic.
The profile component only passes the initials on to the avatar component and doesn't use them anywhere else, so there is no need for it to calculated them. So I've removed the initials logic from the profile component and it now falls through to the avatar component to calculate them.
Now both match and are consistent.
Fixes livewire/flux#1737
> Fix profile initials

- stubs/resources/views/flux/text.blade.php
Currently if you use the `<flux:text>` component it renders a `<div>` instead of a `<p>` tag. It's currently documented in the `inline` prop section of that docs that it is a `<p>` tag by default `If true, the text element will be a span instead of a p.`.
```blade
<flux:text>Some text</flux:text>
```
The issue is that it is expected that it would render a `<p>` tag by default and render a `<span>` when it's inline.
But currently it outputs a `<div>`.
If you need a `<p>` tag, then you have to do the following which feels wrong.
```blade
<flux:text><p>Some text</p></flux:text>
```
This PR changes it so it renders a `<p>` instead of a `<div>` which is more semantic anyway.
Fixes livewire/flux#1735
> Fix text component to use `<p>` tag

- stubs/resources/views/flux/error.blade.php
Currently if you are using Laravel's named error bag feature, the error component can't show errors from a named error bag.
```blade
@php
$errorBag = $errors->getBag('other');
$errorBag->add('name', 'Other Bag: Name is required');
$errors->put('other', $errorBag);
@endphp
<flux:error name="name" />
```
The issue is that the error component doesn't support named error bags. It accesses error messages by calling `$errors->first($name)` which will always resolve from the `default` error bag.
This PR adds a `bag` prop to the error component so a named error bag can be specified.
```blade
<flux:error name="name" bag="other" />
```
I originally had `errorBag`, but I didn't like the multiword, so changed it to just `bag`.
Fixes livewire/flux#1841
> Add named error bag support to error component

- dist/flux.css
Currently if you have a toast stack inside `@persist` with dark mode enabled, and you navigate to a new page, the toast will flash white for a moment before during dark again.
```blade
@persist('toast')
<flux:toast.group>
<flux:toast /> 
</flux:toast.group>
@endpersist
```
```blade
<div>
<flux:button x-on:click="window.Flux.toast({
heading: 'Changes saved',
text: 'Your changes have been saved.',
variant: 'success',
duration: 0,
})">
Dispatch toast
</flux:button>
<flux:link href="/toasts-flash" class="block! mt-4" wire:navigate>Navigate to toasts page</flux:link>
</div>
```
This issue sent me down a rabbit hole of navigate requests and dark mode flashes which there is a deeper issue in how Livewire and Flux handle re-applying dark mode after a navigate (see #1501 and #1842). But I was …
> Fix toast stack dark mode navigate flash

- src/Console/IconCommand.php
When creating a lucide icon using the artisan command, the `@pure` directive was missing.
> Add `@pure` annotation to Lucide IconCommand stub

- stubs/resources/views/flux/sidebar/group.blade.php
- stubs/resources/views/flux/sidebar/item.blade.php
Currently, with the new collapsible sidebar, if we have a sidebar group, the group disappears when the sidebar is collapsed.
The problem is that we have no handling for what to do with a group when it is collapsed. Unlike other sidebar items, which are still clickable to navigate when collapsed, a group needs extra handling as at the moment clicking it will just expand/collapse the group but nothing can be seen.
The solution is to add support for showing a sidebar group's items in a dropdown when the sidebar is collapsed. The dropdown will open when the group's icon is hovered, which feels natural as the tooltips also appear on hover.
**Note:** One thing to note, the `sidebar.group` needs to have an icon (not the default chevron) otherwise it won't be shown, because a stack of chevrons …
> Add sidebar group icon dropdowns

- stubs/resources/views/flux/modal/index.blade.php
Currently the modal close button doesn't have the correct label for screen readers, it just reads "Button".
The issue is that the close button has `alt="Close modal"` but it should be `aria-label="Close modal"`.
This PR changes the `alt="Close modal"` to `aria-label="Close modal"
Fixes livewire/flux#1943
> Fix modal close button aria label
